---
- name: Get the host ip
  shell: getent ahostsv4 $(hostname -f) | grep -v '127.0' | grep 'STREAM' | awk '{print $1}'
  register: host_ip_internal

- name: Get the host ip external (natted)
  shell: host $(hostname -f) | awk '{print $(NF)}'
  register: host_ip_external_natted
  when: host_natted

- name: Get the host ip external
  shell: getent ahostsv4  $(hostname -f) | grep -v '127.0' | grep 'STREAM' | awk '{print $1}'
  register: host_ip_external
  when: not host_natted

- name: Set the host ip
  shell: echo {{ host_ip_external_natted.stdout | default(host_ip_external.stdout) }}
  register: host_ip_external

- name: Get the rethinkdb master IP
  shell: getent ahostsv4 {{ groups['swarm_managers'][0] }} | grep -v '127.0' | grep 'STREAM' | awk '{print $1}'
  register: rethinkdb_ip
  when: not host_natted

- name: Get the rethinkdb master IP (natted)
  shell: host {{ groups['swarm_managers'][0] }} | awk '{print $(NF)}'
  register: rethinkdb_ip_natted
  when: host_natted

- name: Set the rethinkdb master IP
  shell: echo {{ rethinkdb_ip_natted.stdout | default(rethinkdb_ip.stdout) }}
  register: rethinkdb_ip
